[package]
name = "artisyn"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.9.4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.4"
openzeppelin = "1.0.0"

[[target.starknet-contract]]
casm = true

[dev-dependencies]
cairo_test = "2.9.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.44.0" }
